steps:
  # Step 1: Run unit tests
  - name: 'python:3.9-slim'
    id: 'run-tests'
    entrypoint: /bin/sh
    args:
      - -c
      - |
        pip install -r requirements.txt
        cd app
        python -m unittest discover

  # Step 2: Build and push the container image with kaniko
  - name: 'gcr.io/kaniko-project/executor:latest'
    id: 'build-and-push'
    args:
      - --destination=us-central1-docker.pkg.dev/$PROJECT_ID/flask-apps/flask-app:$COMMIT_SHA
      - --context=.
      - --cache=true

  # Step 3: Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-to-cloud-run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'flask-app'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/flask-apps/flask-app:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/flask-apps/flask-app:$COMMIT_SHA'

options:
  logging: 'NONE'