logsBucket: gs://my-build-logs-707bucket

steps:
  # Step 1: Run unit tests
  - name: 'python:3.9-slim'
    id: 'run-tests'
    entrypoint: /bin/sh
    args:
      - -c
      - |
        cd app
        pip install -r ../requirements.txt
        python -m unittest discover

  # Step 2: Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-image'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/flask-app:$COMMIT_SHA', '.']

  # Step 3: Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-image'
    args: ['push', 'gcr.io/$PROJECT_ID/flask-app:$COMMIT_SHA']

  # Step 4: Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-to-cloud-run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'flask-app'
      - '--image'
      - 'gcr.io/$PROJECT_ID/flask-app:$COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

images:
  - 'gcr.io/$PROJECT_ID/flask-app:$COMMIT_SHA'

options:
  logging: GCS_ONLY
  logsBucket: 'gs://my-build-logs-707bucket'