steps:
  # Step 1: Run unit tests
  - name: 'python:3.9-slim'
    id: 'run-tests'
    entrypoint: /bin/sh
    args:
      - -c
      - |
        pip install -r requirements.txt
        cd app
        python -m unittest discover

  # Step 2: Deploy to Cloud Run directly from source
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-to-cloud-run'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'flask-app'
      - '--source'
      - '.'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'

options:
  logging: 'NONE'